import type { CareerOverview } from './careerRoadmaps';

/* Base career overviews for the ten original majors' paths (30 paths).
   Merged into PATH_OVERVIEWS in careerRoadmaps.ts. Kept in a separate file
   to keep the main data module readable. */

export const BASE_OVERVIEWS: Record<string, CareerOverview> = {
  'cs-swe': {
    summary: 'Writes, tests, and reviews code to build and maintain software products, spending much of the day reading existing code, debugging, and collaborating in pull requests, standups, and design docs rather than writing new code from scratch.',
    keySkills: ['Data structures and algorithms', 'A production language (Python, Java, Go, or TypeScript)', 'Git and code review workflows', 'System and API design', 'Debugging and reading unfamiliar code', 'Automated testing'],
    outlook: 'Strong long-term demand, but the entry-level market has tightened, with new grads facing more competition than during the 2020-2022 hiring boom.',
    entryTips: ['Build and ship two or three real projects with public GitHub repos, not just coursework', 'Complete at least one internship, ideally by sophomore or junior summer', 'Practice data-structures and algorithms problems for technical interviews', 'Contribute to open source or a campus software organization'],
    licenses: [],
    topEmployers: ['Google, Microsoft, Amazon, Meta, Apple', 'Product companies like Stripe, Datadog, Atlassian', 'Startups and YC-backed companies', 'Banks, retailers, and healthcare firms with large eng orgs'],
    workStyle: 'Typically 40-50 hours a week with strong remote and hybrid options, though on-call rotations and pre-deadline crunch are real.',
    alsoConsider: ['AI/ML Engineer', 'Data Scientist', 'Product Manager'],
  },
  'cs-ml': {
    summary: 'Builds systems that train, fine-tune, deploy, and monitor machine-learning models, spending a lot of time on data pipelines, evaluation, and production infrastructure rather than inventing new algorithms.',
    keySkills: ['Python and PyTorch or TensorFlow', 'Applied statistics and linear algebra', 'Data cleaning and feature engineering', 'MLOps: deployment, monitoring, and serving', 'LLMs, embeddings, and fine-tuning workflows', 'SQL and large-scale data tools'],
    outlook: 'Rapidly growing demand from generative AI, but roles increasingly expect strong software-engineering skills, and research-heavy positions often require a graduate degree.',
    entryTips: ['Build a strong math, statistics, and CS foundation, not just ML courses', 'Build end-to-end projects that deploy a model, not just a notebook', 'Learn modern LLM tooling and evaluation', 'Pursue an ML or data internship; consider a master’s for research roles'],
    licenses: [],
    topEmployers: ['OpenAI, Anthropic, Google DeepMind', 'Meta, Microsoft, Amazon, Nvidia', 'AI startups and applied-AI teams', 'Finance, healthcare, and autonomous-vehicle firms'],
    workStyle: 'Fast-moving and intellectually intense, generally 45-55 hours a week, with pressure spiking around launches and model releases.',
    alsoConsider: ['Software Engineer', 'Data Scientist', 'Quantitative Analyst'],
  },
  'cs-pm': {
    summary: 'Decides what a software product should do and why, translating user needs and business goals into a prioritized roadmap while coordinating engineers, designers, and stakeholders; the day is mostly meetings, writing specs, and analyzing metrics.',
    keySkills: ['Product sense and user empathy', 'Prioritization and roadmap tradeoffs', 'Data analysis and metrics', 'Clear written and verbal communication', 'Cross-functional influence without authority', 'Enough technical fluency to work with engineers'],
    outlook: 'Competitive field with few true entry-level openings, since many PMs transition in from engineering, consulting, or a rotational program rather than straight from college.',
    entryTips: ['Apply to associate PM (APM) programs at Google, Meta, Uber, and similar', 'Gain a technical or analytical background first', 'Ship a side project or lead a student-org product to show ownership', 'Build a portfolio of product teardowns and case studies'],
    licenses: [],
    topEmployers: ['Google, Meta, Microsoft, Amazon', 'Salesforce, Adobe, Atlassian', 'Startups and growth-stage tech companies', 'Fintech, e-commerce, and enterprise SaaS'],
    workStyle: 'Typically 45-55 hours a week with a high meeting load and always-on communication, though rarely the deep-focus hours engineers keep.',
    alsoConsider: ['Software Engineer', 'Management Consultant', 'UX Researcher'],
  },
  'eng-design': {
    summary: 'Designs mechanical parts and products using CAD, running simulations, building prototypes, and iterating toward a manufacturable design; time splits between modeling, analysis, lab testing, and coordinating with manufacturing.',
    keySkills: ['CAD tools such as SolidWorks or CATIA', 'Statics, materials, and thermodynamics', 'Finite-element analysis and simulation', 'Design for manufacturability and GD&T', 'Prototyping and hands-on testing', 'Technical documentation'],
    outlook: 'Steady, moderate demand across industries; growth is modest but roles are stable and spread across manufacturing hubs, not just coastal tech.',
    entryTips: ['Join a hands-on design team (FSAE, robotics, rocketry)', 'Master one CAD package deeply and build a design portfolio', 'Complete co-ops or internships in a design role', 'Learn manufacturing processes so your designs are buildable'],
    licenses: ['Professional Engineer (PE) license optional but valued (FE exam, then PE exam)'],
    topEmployers: ['Automotive firms like Ford, GM, Tesla', 'Consumer product and appliance companies', 'Medical-device makers like Medtronic and Stryker', 'Industrial and machinery manufacturers'],
    workStyle: 'Predictable 40-45 hour weeks, mostly on-site for lab and prototype access, with occasional crunch near launches.',
    alsoConsider: ['Manufacturing/Operations Engineer', 'Aerospace Engineer', 'UX/UI Designer'],
  },
  'eng-aero': {
    summary: 'Designs, analyzes, and tests aircraft, spacecraft, or their subsystems across aerodynamics, propulsion, structures, or controls; day-to-day mixes simulation, CAD, test-data analysis, and heavy documentation for safety and compliance.',
    keySkills: ['Fluid dynamics and aerodynamics', 'Structural analysis and materials', 'MATLAB and simulation tools', 'Propulsion or controls fundamentals', 'CAD and systems engineering', 'Rigorous testing and requirements tracing'],
    outlook: 'Solid demand from commercial space, defense, and aviation, but many jobs require US citizenship for security clearances, which narrows options.',
    entryTips: ['Join a rocketry, UAV, or design-build-fly team', 'Target internships at aerospace primes or space startups early', 'Note that clearance-eligible (US citizen) candidates have far more options', 'Develop strong programming and simulation skills, not just theory'],
    licenses: ['PE license optional; some defense roles require a security clearance'],
    topEmployers: ['SpaceX, Blue Origin, Rocket Lab', 'Boeing, Lockheed Martin, Northrop Grumman', 'NASA and its contractors', 'Raytheon, GE Aerospace, and defense suppliers'],
    workStyle: 'Generally 45-50 hour weeks, on-site and rigorous, with intense periods around launches, test campaigns, or milestones.',
    alsoConsider: ['Design Engineer', 'Manufacturing/Operations Engineer', 'Software Engineer'],
  },
  'eng-mfg': {
    summary: 'Keeps production lines running efficiently by improving processes, reducing defects and downtime, and scaling manufacturing; spends much of the day on the floor troubleshooting, analyzing production data, and driving continuous improvement.',
    keySkills: ['Lean manufacturing and Six Sigma', 'Process optimization and root-cause analysis', 'Statistical process control', 'CAD and reading engineering drawings', 'Supply chain and quality basics', 'Communicating with operators and management'],
    outlook: 'Reliable demand strengthened by reshoring and semiconductor investment, with strong opportunities outside coastal tech hubs.',
    entryTips: ['Do a manufacturing co-op or plant internship', 'Pursue Lean or Six Sigma (Green Belt) certification', 'Get comfortable working with floor operators and machinery', 'Build data-analysis skills to support process decisions'],
    licenses: ['PE license optional; Six Sigma belts are common credentials'],
    topEmployers: ['Intel, TSMC, and semiconductor fabs', 'Automotive and aerospace manufacturers', 'Consumer-goods firms like Procter & Gamble', 'Medical-device and industrial manufacturers'],
    workStyle: 'Usually 45-50 hours a week and plant-based; may include shift work, early hours, or being on call for line issues.',
    alsoConsider: ['Design Engineer', 'Management Consultant', 'Aerospace Engineer'],
  },
  'biz-consulting': {
    summary: 'Helps companies solve business problems by gathering data, building analyses and slide decks, interviewing stakeholders, and presenting recommendations; early years are heavy on Excel modeling, PowerPoint, and client work.',
    keySkills: ['Structured problem-solving and frameworks', 'Excel financial and operational modeling', 'PowerPoint storytelling', 'Data analysis and synthesis', 'Client communication and executive presence', 'Managing ambiguity and tight deadlines'],
    outlook: 'Prestigious and competitive; top firms recruit heavily from target schools and entry is very selective, though the skills transfer widely afterward.',
    entryTips: ['Network and recruit hard, especially if not at a target school', 'Master case interviews through mock cases', 'Build a resume with leadership and quantitative rigor', 'Pursue a strategy internship the summer before senior year'],
    licenses: [],
    topEmployers: ['McKinsey, Bain, BCG (MBB)', 'Deloitte, PwC, EY, KPMG', 'Accenture and strategy boutiques', 'Internal strategy teams at large corporations'],
    workStyle: 'Demanding 55-70 hour weeks with frequent travel or long remote client hours; the pace is a well-known burnout risk.',
    alsoConsider: ['Investment Banking/Finance', 'Product Manager', 'Policy Economist'],
  },
  'biz-finance': {
    summary: 'In investment banking, advises companies on raising capital and on mergers and acquisitions, building financial models and pitch books and running deal processes; analyst years are long and Excel- and PowerPoint-intensive.',
    keySkills: ['Financial modeling and valuation (DCF, comps, LBO)', 'Advanced Excel', 'Accounting and financial-statement analysis', 'PowerPoint pitch books', 'Attention to detail under pressure', 'Professional client communication'],
    outlook: 'Highly competitive and lucrative; recruiting is early and target-school driven, and headcount is cyclical with deal activity and interest rates.',
    entryTips: ['Recruit extremely early, often freshman or sophomore year', 'Land a sophomore program, then a junior analyst internship', 'Learn accounting and valuation cold before interviews', 'Network relentlessly with alumni and bankers'],
    licenses: ['SIE and FINRA Series 79 and 63 (on the job); CFA optional for investing roles'],
    topEmployers: ['Goldman Sachs, Morgan Stanley, JPMorgan', 'Bank of America, Citi, other bulge brackets', 'Evercore, Centerview, elite boutiques', 'Private equity and hedge funds (exit paths)'],
    workStyle: 'Notoriously grueling analyst years of 70-90+ hours a week including nights and weekends, with pay that reflects the intensity.',
    alsoConsider: ['Quantitative Analyst', 'Management Consultant', 'Data Scientist'],
  },
  'biz-entrepreneur': {
    summary: 'Builds a business from an idea, which in practice means constantly selling, recruiting, fundraising, building product, and doing whatever unglamorous task the company needs that day; the founder wears every hat early on.',
    keySkills: ['Selling and persuasion', 'Rapid learning and adaptability', 'Resourcefulness and resilience', 'Basic finance, product, and marketing literacy', 'Recruiting and team-building', 'Comfort with risk and uncertainty'],
    outlook: 'High-variance path where most startups fail, but the skills and network compound, and many founders start after gaining experience elsewhere first.',
    entryTips: ['Start something small and real while in school', 'Join an early-stage startup to see how companies are built', 'Build a network of potential co-founders, mentors, and customers', 'Develop a concrete, valuable skill (engineering, sales, design)'],
    licenses: [],
    topEmployers: ['Self-employed founder', 'Accelerators like Y Combinator and Techstars', 'Early-stage startups as a founding employee', 'University entrepreneurship programs and incubators'],
    workStyle: 'Long, unpredictable hours with real financial stress and little work-life separation, especially in the early years.',
    alsoConsider: ['Product Manager', 'Management Consultant', 'Software Engineer'],
  },
  'bio-md': {
    summary: 'Diagnoses and treats patients, which depending on specialty means clinic visits, procedures or surgery, managing hospital care, and extensive documentation; the role carries high responsibility and continuous learning.',
    keySkills: ['Strong science foundation (biology, chemistry, physiology)', 'Clinical reasoning and diagnosis', 'Patient communication and empathy', 'Stamina and emotional resilience', 'Attention to detail and safety', 'Teamwork with nurses and staff'],
    outlook: 'Reliable, strong demand especially in primary care and underserved areas, but the path is long, expensive, and requires sustained top academic performance.',
    entryTips: ['Excel in prerequisite sciences and the MCAT', 'Get clinical exposure (shadowing, scribing, EMT, or CNA)', 'Build research and volunteering experience for applications', 'Understand the timeline: 4 years med school plus 3-7 years residency'],
    licenses: ['USMLE Steps 1, 2, and 3; state medical license; specialty board certification'],
    topEmployers: ['Academic medical centers and university hospitals', 'Systems like Kaiser, Mayo Clinic, Cleveland Clinic', 'Private group practices', 'Community hospitals and the VA'],
    workStyle: 'Long training years and often 50-60+ hour weeks with call, though lifestyle varies enormously by specialty.',
    alsoConsider: ['Nurse Anesthetist (CRNA)', 'Biomedical Researcher', 'Clinical Nurse to Nurse Practitioner'],
  },
  'bio-research': {
    summary: 'Investigates biological questions by designing and running experiments, analyzing data, and publishing findings; daily life is bench or computational work, reading literature, troubleshooting protocols, and writing papers and grants.',
    keySkills: ['Experimental design and lab techniques', 'Data analysis and statistics', 'Scientific writing and literature review', 'Coding in Python or R for bioinformatics', 'Persistence through failed experiments', 'Grant writing (for PIs)'],
    outlook: 'Meaningful work but an oversupplied academic job market; a PhD is typically required and faculty positions are scarce, pushing many into industry.',
    entryTips: ['Join a research lab as an undergraduate as early as possible', 'Aim to be a co-author on a publication', 'Consider a funded PhD rather than paying for a master’s', 'Build computational skills to broaden into industry'],
    licenses: ['PhD effectively required for independent research roles'],
    topEmployers: ['Universities and academic medical centers', 'NIH and national laboratories', 'Institutes like Broad, HHMI, and Salk', 'Biotech and pharma R&D as an industry path'],
    workStyle: 'Flexible but long hours governed by experiments; academic pay is modest and progress depends on publications and grants.',
    alsoConsider: ['Biotech/Pharma', 'Physician (MD)', 'Data Scientist'],
  },
  'bio-biotech': {
    summary: 'Develops drugs, therapies, or biological products in industry, in roles from bench research and process development to clinical trials and regulatory affairs; the work is team-based, milestone-driven, and tied to product pipelines.',
    keySkills: ['Molecular biology and biochemistry lab methods', 'Assay development and data analysis', 'Drug development and clinical-trial knowledge', 'GMP and regulatory awareness', 'Cross-functional collaboration', 'Documentation and reproducibility'],
    outlook: 'Growing but cyclical field sensitive to biotech funding; hubs like Boston and San Francisco offer the most roles, and advanced degrees help for research tracks.',
    entryTips: ['Get lab research experience and learn industry techniques', 'Pursue internships or co-ops at biotech or pharma companies', 'Consider a master’s or PhD for scientist-track roles', 'Learn adjacent skills like data analysis or regulatory basics'],
    licenses: [],
    topEmployers: ['Pfizer, Merck, Genentech, Amgen', 'Moderna, Vertex, Regeneron', 'Contract research and manufacturing organizations', 'Biotech startups in Boston, San Diego, the Bay Area'],
    workStyle: 'Generally 40-50 hour weeks with better balance than academia, though layoffs track industry funding cycles.',
    alsoConsider: ['Biomedical Researcher', 'Manufacturing/Operations Engineer', 'Data Scientist'],
  },
  'nurs-clinical': {
    summary: 'Provides direct patient care — assessing patients, administering medications, coordinating with physicians, and educating families; many nurses later earn an advanced degree to become a nurse practitioner who can diagnose and prescribe.',
    keySkills: ['Clinical assessment and patient care', 'Pharmacology and medication safety', 'Communication and patient education', 'Critical thinking under pressure', 'Time management across patients', 'Compassion and emotional resilience'],
    outlook: 'Strong, durable demand amid ongoing nursing shortages, and nurse practitioner roles are among the fastest-growing healthcare jobs.',
    entryTips: ['Earn a BSN rather than only an associate degree', 'Get hospital experience, often in med-surg or a specialty unit', 'Gain a few years of RN experience before NP programs', 'Choose an NP specialty (family, acute care, psych) intentionally'],
    licenses: ['NCLEX-RN for licensure; national NP certification and state APRN license for NPs'],
    topEmployers: ['Hospitals and health systems', 'Outpatient clinics and physician practices', 'Kaiser Permanente, HCA, academic medical centers', 'Community health and specialty centers'],
    workStyle: 'Bedside nursing means physically demanding 12-hour shifts including nights, weekends, and holidays; NP roles shift toward clinic hours.',
    alsoConsider: ['Nurse Anesthetist (CRNA)', 'Physician (MD)', 'Nurse Administrator'],
  },
  'nurs-admin': {
    summary: 'Manages nursing units, staff, budgets, and operations rather than providing bedside care — handling scheduling, hiring, quality and safety metrics, and policy; the role blends healthcare knowledge with people and business management.',
    keySkills: ['Leadership and staff management', 'Healthcare operations and budgeting', 'Quality improvement and compliance', 'Staffing and outcomes data', 'Conflict resolution and communication', 'A clinical background to earn staff trust'],
    outlook: 'Solid demand as health systems consolidate and need experienced clinical leaders, with growth in management and executive nursing roles.',
    entryTips: ['Build several years of clinical RN experience first', 'Pursue an MSN in leadership or an MHA/MBA', 'Take on charge-nurse or committee roles', 'Learn healthcare finance and quality metrics'],
    licenses: ['RN license required; NEA-BC or CENP certification and a graduate degree common for senior roles'],
    topEmployers: ['Hospitals and integrated health systems', 'Long-term care and outpatient organizations', 'Kaiser Permanente, HCA, Ascension', 'Government and veterans health facilities'],
    workStyle: 'More predictable daytime hours than bedside nursing, though on-call responsibility for the unit and administrative pressure remain.',
    alsoConsider: ['Clinical Nurse to Nurse Practitioner', 'Management Consultant', 'Government/Public Service'],
  },
  'nurs-crna': {
    summary: 'Administers anesthesia and monitors patients before, during, and after surgery, working closely with surgeons and anesthesiologists; one of the most autonomous and highest-paid advanced-practice nursing roles.',
    keySkills: ['Advanced pharmacology and physiology', 'Airway management and anesthesia delivery', 'Vigilant real-time monitoring', 'Rapid crisis response and calm under pressure', 'Precision and attention to detail', 'A strong critical-care foundation'],
    outlook: 'Excellent demand with very high pay, but entry is extremely competitive and the required doctoral programs are demanding and now standard.',
    entryTips: ['Earn a BSN and excel academically', 'Gain 1-2 years of ICU critical-care experience', 'Obtain CCRN certification to strengthen your application', 'Prepare for a rigorous doctoral (DNP or DNAP) anesthesia program'],
    licenses: ['RN license, critical-care experience, doctoral CRNA program, and the National Certification Exam (NCE)'],
    topEmployers: ['Hospital surgical departments', 'Ambulatory surgery centers', 'Anesthesia group practices', 'Rural and critical-access hospitals'],
    workStyle: 'Strong pay with variable schedules that can include long OR days, call, and early starts depending on the setting.',
    alsoConsider: ['Physician (MD)', 'Clinical Nurse to Nurse Practitioner', 'Biomedical Researcher'],
  },
  'psych-clinical': {
    summary: 'Assesses and treats mental-health conditions through therapy, psychological testing, and diagnosis, and sometimes research; days are filled with client sessions, writing notes and assessments, and treatment planning.',
    keySkills: ['Clinical assessment and diagnosis', 'Evidence-based therapy such as CBT', 'Active listening and rapport-building', 'Research and statistics (for doctoral training)', 'Ethical judgment and boundaries', 'Emotional regulation and self-care'],
    outlook: 'Rising demand for mental-health services, but the path requires a doctorate plus supervised hours and licensure — a long, credential-heavy road.',
    entryTips: ['Major in psychology and get research or clinical volunteer experience', 'Target a funded PhD (research) or PsyD (practice) program', 'Complete supervised clinical hours and internships', 'Decide early between practice, research, and testing focuses'],
    licenses: ['Doctorate (PhD or PsyD), supervised hours, and the EPPP licensing exam'],
    topEmployers: ['Private practices and group clinics', 'Hospitals and community mental-health centers', 'University counseling centers', 'The VA, correctional, or school systems'],
    workStyle: 'Often controllable hours, especially in private practice, but emotionally demanding work with real risk of compassion fatigue.',
    alsoConsider: ['Industrial-Organizational Psychologist', 'UX Researcher', 'Biomedical Researcher'],
  },
  'psych-io': {
    summary: 'Applies psychology to workplaces — improving hiring, engagement, training, team performance, and organizational design; work mixes running surveys and studies, analyzing data, and advising HR and leadership.',
    keySkills: ['Research design and statistics', 'Survey and assessment development', 'Data analysis in R, SPSS, or Python', 'People analytics and psychometrics', 'Consulting and stakeholder communication', 'Organizational behavior'],
    outlook: 'One of the more employable psychology tracks, with demand in people analytics and talent, though many roles want a master’s or PhD.',
    entryTips: ['Build strong quantitative and statistics skills', 'Pursue a master’s or PhD in I-O psychology', 'Intern in HR analytics, talent, or consulting', 'Learn data tools to compete for people-analytics roles'],
    licenses: [],
    topEmployers: ['Corporate people-analytics and HR teams', 'Consulting firms like Korn Ferry and Gallup', 'Assessment companies such as SHL and DDI', 'Government and military personnel research'],
    workStyle: 'Typical 40-45 hour business-hours weeks with good work-life balance and growing remote options.',
    alsoConsider: ['UX Researcher', 'Data Scientist', 'Management Consultant'],
  },
  'psych-ux': {
    summary: 'Studies how people use products by planning and running interviews, usability tests, and surveys, then turning findings into recommendations that shape design and product decisions; days mix talking to users, analyzing data, and presenting insights.',
    keySkills: ['Qualitative interviewing and usability testing', 'Survey design and quantitative analysis', 'Synthesizing findings into recommendations', 'Research planning and participant recruiting', 'Storytelling with stakeholders', 'A basic grasp of design and product'],
    outlook: 'Valued but competitive, and hiring softened after the tech contraction; researchers who can also handle quantitative work are best positioned.',
    entryTips: ['Build a portfolio of research projects, even from coursework', 'Learn both qualitative and quantitative methods', 'Do a UX research internship or related research role', 'Leverage a psychology, HCI, or social-science background'],
    licenses: [],
    topEmployers: ['Google, Microsoft, Meta, Amazon', 'Design-driven product companies', 'UX consultancies and agencies', 'Fintech, healthcare, and enterprise software'],
    workStyle: 'Generally balanced 40-45 hour weeks with strong remote options, though timelines compress around product deadlines.',
    alsoConsider: ['UX/UI Designer', 'Industrial-Organizational Psychologist', 'Product Manager'],
  },
  'econ-policy': {
    summary: 'Analyzes how policies and economic conditions affect people and markets — building models, running data analysis, and writing reports that inform government, think tanks, or international bodies; research- and writing-heavy work.',
    keySkills: ['Econometrics and statistical analysis', 'Data tools like Stata, R, or Python', 'Economic theory applied to real problems', 'Clear technical writing and briefing', 'Critical evaluation of evidence', 'Explaining findings to non-economists'],
    outlook: 'Steady demand in government and research institutions, though the most influential roles usually require a master’s or PhD.',
    entryTips: ['Take rigorous econ, math, and statistics coursework', 'Learn a statistical programming language well', 'Seek a research-assistant role at a think tank or agency', 'Consider a master’s in economics or public policy'],
    licenses: ['PhD common for senior research economist roles'],
    topEmployers: ['Federal Reserve and agencies (CBO, BLS, Treasury)', 'Think tanks like Brookings, RAND, Urban Institute', 'The World Bank and IMF', 'Consulting and university research centers'],
    workStyle: 'Predictable roughly 40-hour weeks in most public-sector roles, with deadline pushes around reports and policy cycles.',
    alsoConsider: ['Data Scientist', 'Government/Public Service', 'Quantitative Analyst'],
  },
  'econ-data': {
    summary: 'Turns data into insights and models to guide decisions, spending most of the time cleaning and querying data, building analyses and dashboards, running experiments, and occasionally training models — more SQL-heavy than the hype suggests.',
    keySkills: ['SQL and data wrangling', 'Python or R for analysis', 'Statistics and A/B testing', 'Data visualization and dashboards', 'Communicating insights to stakeholders', 'Machine-learning fundamentals'],
    outlook: 'Healthy demand, though the title spans everything from analytics to ML; strong SQL, statistics, and communication skills matter more than fancy models.',
    entryTips: ['Build projects using real, messy datasets and share them', 'Master SQL and core statistics before advanced ML', 'Do a data or analytics internship', 'Learn to communicate findings clearly, not just build models'],
    licenses: [],
    topEmployers: ['Tech companies like Google, Meta, Netflix', 'Banks, retailers, and healthcare firms', 'Consulting and analytics companies', 'Startups and any data-rich business'],
    workStyle: 'Usually balanced 40-45 hour weeks with strong remote options, with pressure tied to reporting cycles and stakeholder requests.',
    alsoConsider: ['AI/ML Engineer', 'Quantitative Analyst', 'Policy Economist'],
  },
  'econ-quant': {
    summary: 'Builds mathematical models to price assets, manage risk, or drive trading strategies at banks and funds, combining heavy math, statistics, and programming; days involve researching signals, coding models, and validating them against market data.',
    keySkills: ['Advanced mathematics and probability', 'Statistics and stochastic modeling', 'Strong programming (Python and C++)', 'Financial-markets knowledge', 'Machine learning and data analysis', 'Rigor and precision under uncertainty'],
    outlook: 'Highly paid and highly competitive, favoring candidates with graduate degrees in quantitative fields from strong programs.',
    entryTips: ['Pursue deep math, stats, and CS coursework — often a master’s or PhD', 'Practice quantitative and probability interview problems', 'Build coding skills well beyond scripting', 'Compete in trading, math, or data competitions'],
    licenses: ['CFA or FRM optional; advanced degree effectively expected'],
    topEmployers: ['Hedge funds like Citadel, Two Sigma, Jane Street', 'Investment banks quant and risk desks', 'Proprietary trading firms', 'Asset managers and fintech firms'],
    workStyle: 'Intense and high-pressure, often 50-60 hours a week, with compensation that reflects the difficulty.',
    alsoConsider: ['Data Scientist', 'AI/ML Engineer', 'Investment Banking/Finance'],
  },
  'poli-law': {
    summary: 'Advises and represents clients on legal matters — drafting contracts and documents, researching law, negotiating, and sometimes litigating; junior lawyers do extensive research, writing, and document review.',
    keySkills: ['Legal research and analysis', 'Persuasive writing and argumentation', 'Attention to detail', 'Negotiation and advocacy', 'Interpreting complex text', 'Time and case management'],
    outlook: 'Stable but stratified: elite firm jobs are competitive and lucrative while many graduates face high debt and a tighter mid-market, so law-school choice matters.',
    entryTips: ['Build a strong GPA and prepare seriously for the LSAT', 'Aim for the best-value law school, weighing debt against outcomes', 'Get legal internships or paralegal work to confirm interest', 'Secure a summer associate position during law school'],
    licenses: ['JD degree, the state bar exam, and the MPRE ethics exam'],
    topEmployers: ['Big Law firms like Kirkland & Ellis and Latham', 'Government (DOJ, district attorneys, public defenders)', 'In-house corporate legal departments', 'Public-interest and nonprofit organizations'],
    workStyle: 'Big Law means 60-80 hour weeks and billable-hour pressure; government and in-house roles are more balanced but pay less.',
    alsoConsider: ['Government/Public Service', 'International Relations/Diplomacy', 'Management Consultant'],
  },
  'poli-govt': {
    summary: 'Serves the public through roles in agencies, legislatures, or local government — policy analysis, program management, constituent services, or administration; work centers on making government function and implementing policy.',
    keySkills: ['Policy analysis and research', 'Writing memos and briefs', 'Stakeholder and constituent communication', 'Understanding how government works', 'Budgeting and program management', 'Collaboration across bureaucracies'],
    outlook: 'Stable employment with good benefits and job security, though pay lags the private sector and advancement can be slow.',
    entryTips: ['Intern with a government office, campaign, or agency', 'Consider fellowships like Presidential Management Fellows', 'Build writing and analytical skills', 'Network within the level and area of government you want'],
    licenses: [],
    topEmployers: ['Federal agencies and Congress', 'State and local governments', 'Public agencies and school districts', 'Nonprofits and advocacy organizations'],
    workStyle: 'Generally stable 40-hour weeks with strong benefits, though campaign and legislative-session periods can be intense.',
    alsoConsider: ['Attorney', 'International Relations/Diplomacy', 'Policy Economist'],
  },
  'poli-intl': {
    summary: 'Works on relations between countries through diplomacy, international development, or global policy — analyzing foreign affairs, writing reports, and representing or advising on interests abroad; entry roles are analytical and writing-heavy.',
    keySkills: ['Regional and geopolitical knowledge', 'Foreign-language proficiency', 'Analytical writing and briefing', 'Cross-cultural communication', 'Negotiation and diplomacy', 'Research on international issues'],
    outlook: 'Prestigious but limited in openings; the Foreign Service is very competitive, and many roles favor graduate degrees and language skills.',
    entryTips: ['Develop fluency in a strategically useful language', 'Study abroad and gain international experience', 'Intern at the State Department, an NGO, or an international body', 'Consider the Foreign Service exam or a policy master’s'],
    licenses: ['Foreign Service Officer Test and assessment for diplomatic careers'],
    topEmployers: ['US State Department and USAID', 'United Nations and international organizations', 'Think tanks and NGOs', 'Multinational corporations global-affairs teams'],
    workStyle: 'Diplomatic careers involve relocation and overseas postings; hours vary and can spike during crises or negotiations.',
    alsoConsider: ['Government/Public Service', 'Attorney', 'Policy Economist'],
  },
  'comm-marketing': {
    summary: 'Shapes how a brand is positioned and how products are promoted — running campaigns, analyzing customer data and performance, managing content and channels, and coordinating with creative and sales teams.',
    keySkills: ['Marketing strategy and positioning', 'Data analysis and campaign metrics', 'Copywriting and messaging', 'Digital channels: SEO, social, email, paid ads', 'Project management across teams', 'Understanding the target audience'],
    outlook: 'Broad, accessible field with steady demand, though competitive at the top and increasingly rewarding data and digital fluency over pure creativity.',
    entryTips: ['Do marketing internships and build a portfolio of campaigns', 'Run your own small projects (a blog, social account, or store)', 'Get certified in Google Analytics or ad platforms', 'Choose a lane: brand, growth, content, or product marketing'],
    licenses: [],
    topEmployers: ['Consumer brands like Procter & Gamble, Nike, Unilever', 'Tech companies and their growth teams', 'Advertising and marketing agencies', 'E-commerce and direct-to-consumer companies'],
    workStyle: 'Typically 40-50 hour weeks with good remote flexibility, busier around campaign launches and product cycles.',
    alsoConsider: ['Public Relations', 'Media Producer/Content', 'Product Manager'],
  },
  'comm-pr': {
    summary: "Manages an organization's public image and communications — writing press releases and messaging, building media relationships, handling crises, and coordinating announcements; fast-paced and reactive to the news.",
    keySkills: ['Strong writing and messaging', 'Media relations and pitching', 'Crisis communication', 'Storytelling and framing', 'Social-media and digital awareness', 'Composure under pressure'],
    outlook: 'Steady but competitive, evolving as earned media blends with social and influencer channels; strong writers who understand digital do best.',
    entryTips: ['Intern at a PR agency or in-house communications team', 'Sharpen writing through journalism or the campus paper', 'Build a network of media and industry contacts', 'Craft sample pitches and press materials for a portfolio'],
    licenses: [],
    topEmployers: ['PR agencies like Edelman and Weber Shandwick', 'Corporate communications departments', 'Nonprofits and advocacy groups', 'Government and political communications offices'],
    workStyle: 'Deadline-driven with real potential for after-hours crisis work, since news does not keep business hours.',
    alsoConsider: ['Marketing/Brand Strategy', 'Media Producer/Content', 'Government/Public Service'],
  },
  'comm-media': {
    summary: 'Creates video, audio, or written content for audiences — planning, filming or recording, editing, and publishing; the day depends on the format but centers on producing content on deadline and growing an audience.',
    keySkills: ['Storytelling and scripting', 'Video or audio editing (Premiere, Final Cut, Audition)', 'Production planning and shooting', 'Understanding platform algorithms and audiences', 'Project and time management', 'Adaptability across formats'],
    outlook: 'Growing content demand but a crowded field where pay is uneven and success depends heavily on portfolio, versatility, and audience results.',
    entryTips: ['Create a public body of work: a channel, portfolio, or reel', 'Learn editing tools deeply and develop a distinct style', 'Intern or freelance with a studio, brand, or media company', 'Learn what performs on each platform and why'],
    licenses: [],
    topEmployers: ['Media and streaming companies like Netflix, NBCUniversal', 'In-house brand content teams', 'Production studios and agencies', 'Digital publishers and creator-economy platforms'],
    workStyle: 'Project-based with irregular hours around shoots and deadlines; freelance paths offer freedom but unstable income.',
    alsoConsider: ['Marketing/Brand Strategy', 'Public Relations', 'Graphic Designer/Brand'],
  },
  'art-ux': {
    summary: 'Designs how digital products look and work — creating wireframes, prototypes, and polished interfaces in tools like Figma and iterating on user feedback and developer constraints; blends visual design with interaction and problem-solving.',
    keySkills: ['Figma and prototyping', 'Interaction and information architecture', 'Visual design: layout, typography, color', 'Design systems and components', 'User empathy and usability principles', 'Collaboration with engineers and PMs'],
    outlook: 'Competitive market that cooled after the tech slowdown, with entry-level roles especially crowded; a strong portfolio is the main differentiator.',
    entryTips: ['Build a portfolio of 2-4 deep case studies showing your process', 'Master Figma and study strong design systems', 'Redesign real products as practice projects', 'Do a UX internship or freelance for real-world work'],
    licenses: [],
    topEmployers: ['Tech companies like Google, Apple, Airbnb', 'Design agencies and studios', 'Startups and product companies', 'Enterprise-software and fintech firms'],
    workStyle: 'Generally balanced 40-45 hour weeks with strong remote options, with crunch near product launches.',
    alsoConsider: ['UX Researcher', 'Graphic Designer/Brand', 'Product Manager'],
  },
  'art-graphic': {
    summary: 'Creates visual designs and brand identities — logos, marketing materials, packaging, and layouts — in Adobe tools, solving communication problems visually; roles range from in-house brand work to fast-turnaround agency projects.',
    keySkills: ['Adobe Creative Suite (Illustrator, Photoshop, InDesign)', 'Typography and layout', 'Color theory and composition', 'Brand identity and systems thinking', 'Applying creative feedback', 'Some motion or web design as a plus'],
    outlook: 'Steady but competitive, with routine work pressured by templates and AI tools; designers who think strategically about brand fare much better.',
    entryTips: ['Build a strong, curated portfolio that shows range and thinking', 'Master typography, which separates amateurs from pros', 'Freelance or intern to get real client work', 'Learn adjacent skills like motion, web, or brand strategy'],
    licenses: [],
    topEmployers: ['Design and branding agencies', 'In-house brand and marketing teams', 'Publishing and media companies', 'Freelance and studio work'],
    workStyle: 'Usually 40-45 hour weeks, though agencies run long around deadlines; freelancing trades stability for flexibility.',
    alsoConsider: ['UX/UI Designer', 'Marketing/Brand Strategy', 'Media Producer/Content'],
  },
  'art-arch': {
    summary: 'Designs buildings and spaces, balancing aesthetics, function, budget, and codes, producing drawings and models and coordinating with engineers, clients, and contractors; early-career work is heavy on drafting, detailing, and documentation.',
    keySkills: ['Design and spatial thinking', 'CAD and BIM tools like Revit and AutoCAD', '3D modeling and rendering', 'Building codes and construction knowledge', 'Client and consultant communication', 'Balancing creativity with constraints'],
    outlook: 'Modest growth and a long, credential-heavy path with relatively low early pay for the education required; sustainability and computational design are growth areas.',
    entryTips: ['Complete an accredited (NAAB) architecture degree', 'Build a strong design portfolio throughout school', 'Intern at firms and log hours toward licensure (AXP)', 'Learn Revit and rendering tools employers expect'],
    licenses: ['NAAB-accredited degree, AXP hours, and the Architect Registration Exam (ARE)'],
    topEmployers: ['Architecture firms like Gensler, HOK, Perkins&Will', 'Boutique and residential design studios', 'Government and institutional planning offices', 'Real-estate developers and construction firms'],
    workStyle: 'Typically 45-50 hour weeks with deadline crunches; the early years are known for long hours relative to the pay.',
    alsoConsider: ['Design Engineer', 'UX/UI Designer', 'Graphic Designer/Brand'],
  },
};
